name: acquaintance
description: A new Flutter project.

publish_to:

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.4
  json_annotation: ^4.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  build_runner:
  json_serializable: ^4.1.3
  flutter_svg: ^1.0.3


flutter:
  assets:
    - assets/icons/

  uses-material-design: true

